import type { Metadata } from 'next'
import ApiProvider from '@api/services/provider'
import { SidebarProvider, SidebarTrigger } from '@/shadcn/components/ui/sidebar'
import { AppSidebar } from '@components/Sidebar/Sidebar'
import ReduxProvider from './redux/provider'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <ApiProvider>
            <SidebarProvider>
              <AppSidebar />
              <SidebarTrigger />
              <main className="max-w-[calc(100%-260px)] mx-auto">
                {children}
              </main>
            </SidebarProvider>
          </ApiProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}
